
language: java
jdk: oraclejdk9


cache:
  directories:
    - $HOME/.m2


notifications:
  email:
    recipients:
      - qThegamEp@gmail.com
    on_success: always # default: change
    on_failure: always # default: always