version: '3'
services:
  app:
    image: 'esdpteam2java11/a-2_automation_system:GO_PIPELINE_COUNTER'
    build:
      context: .
    container_name: app
    volumes:
      - a2app:/home/a2app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgresDB
      - SPRING_DATASOURCE_USERNAME=postgresUser
      - SPRING_DATASOURCE_PASSWORD=postgresPassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_DB: postgresDB
      
volumes:
    db-data:
    a2app:
       

